export default {

    ARG: "ar",
    AUS: "au",
    BEL: "be",
    BRA: "br",
    CAN: "ca",
    CRO: "hr",
    CZE: "cz",
    DEN: "dk",
    ENG: "gb-eng",
    ESP: "es",
    FRA: "fr",
    GER: "de",
    ITA: "it",
    JPN: "jp",
    KOR: "kr",
    MAR: "ma",
    MEX: "mx",
    NED: "nl",
    NOR: "no",
    POL: "pl",
    POR: "pt",
    ROU: "ro",
    SCO: "gb-sct",
    SRB: "rs",
    SUI: "ch",
    SWE: "se",
    TUR: "tr",
    UKR: "ua",
    URU: "uy",
    USA: "us",

};